### PR TITLE
[Groups] Add styles to wrap group name in header

### PR DESCRIPTION
**Pull request by savathoon**
Before:
Screenshot 2024-11-01 at 11 30 23 AM

After:
Screenshot 2024-11-01 at 11 26 14 AM

### CODE REVIEW

**Review by somethingnew2-0 — APPROVED** [review]

**Comment by amyjchen** [comment]
Screenshot 2024-11-01 at 12 32 40

rebased

**Comment by somethingnew2-0** [comment]
Can we also do it for Apps and Tags?

**Review by somethingnew2-0 — APPROVED** [review]

**Comment by amyjchen** [comment]
| Requests | Role | App | Tags |
| --- | --- | --- | --- |
 | Screenshot 2024-11-01 at 12 58 36 | Screenshot 2024-11-01 at 12 58 51 | Screenshot 2024-11-01 at 12 59 20 | Screenshot 2024-11-01 at 12 59 39 |

**Comment by amyjchen** [comment]
Screenshot 2024-11-01 at 13 11 53

**Pull request merged**
